<?php

/**
 * @file
 * Contains commerce_updates_8_x_2_16.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_updates_8_x_2_16_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_updates_8_x_2_16 module.
    case 'help.page.commerce_updates_8_x_2_16':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Reruns some essential updates for Drupal Commerce when updating from 8.x-2.15 to 8.x-2.16') . '</p>';
      return $output;

    default:
  }
}
